name: Build Openwrt for Amlogic s905x

on:
  workflow_dispatch
  # repository_dispatch:

env:
  OPENWRT_BRANCH: openwrt-21.02
  OPENWRT_REPOSITORY: https://github.com/openwrt/openwrt
  REQUIRED_PACKAGES: install build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils zlib1g-dev
  TZ: Asia/Jakarta
  WORKING_DIR: /WORKING_DIR

jobs:
  build:
    # https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntu
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -qq update
          sudo -E apt -qq install $REQUIRED_PACKAGES
          sudo -E apt -qq autoremove --purge
          sudo -E apt -qq autoremove clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p $WORKING_DIR
          sudo chown $USER:$GROUPS /workdir
          echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV

      - name: Cloning source code
        working-directory: $WORKING_DIR
        run: |
          git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt .
          git clone --depth 1 -b $OPENWRT_BRANCH --single-branch $OPENWRT_REPOSITORY openwrt

