name: Build Openwrt for Amlogic s905x

on:
  # workflow_dispatch
  repository_dispatch:

env:
  CONFIG_DIR: config
  OPENWRT_BRANCH: ${{ github.head_ref }}
  OPENWRT_REPOSITORY: https://github.com/openwrt/openwrt
  REQUIRED_PACKAGES: build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils zlib1g-dev
  TZ: Asia/Jakarta
  WORKING_DIR: /WORKING_DIR

jobs:
  build:
    # https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntu
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $REQUIRED_PACKAGES
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p "$WORKING_DIR"
          sudo chown $USER:$GROUPS "$WORKING_DIR"
          echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV

      - name: Cloning source code
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt .
          git clone --depth 1 -b "$OPENWRT_BRANCH" --single-branch "$OPENWRT_REPOSITORY" openwrt

      - name: Copy configs
        working-directory: ${{ env.WORKING_DIR }}/openwrt
        run: |
          [ -e $CONFIG_DIR ] && cp -rf $CONFIG_DIR/. .
          [ -e ./pre-build.sh ] && chmod +x pre-build.sh && ./pre-build.sh
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV

      - name: Update feeds
        working-directory: ${{ env.WORKING_DIR }}/openwrt
        run: ./scripts/feeds update -a

      - name: Install feeds
        working-directory: ${{ env.WORKING_DIR }}/openwrt
        run: ./scripts/feeds install -a

      - name: Download Packages
        working-directory: ${{ env.WORKING_DIR }}/openwrt
        run: |
          make defconfig
          make -j$(($(nproc) + 1)) download

      - name: Compile Openwrt
        id: compile
        working-directory: ${{ env.WORKING_DIR }}/openwrt
        run: |
          make -j$(($(nproc) + 1)) || make -j1 V=s
          echo "::set-output name=status::success"

      - name: Build Openwrt firmware
        if: steps.compile.outputs.status == 'success' && !cancelled()
        id: build
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          mkdir -p openwrt-armvirt
          cp openwrt/bin/targets/*/*/*rootfs.tar.gz openwrt-armvirt
          sudo ./make -b s905x -k 5.10.125 -a true -v stable
          echo "BUILD_DATE=$(date +"%Y-%m-%d.%H%M")" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Release the firmware
        if: steps.build.outputs.status == 'success' && !cancelled()
        working-directory: ${{ env.WORKING_DIR }}
        uses: ncipollo/release-action@main
        with:
          tag: ${{ DEVICE_NAME }}_${{ env.OPENWRT_BRANCH }}_${{ env.BUILD_DATE }}
          artifacts: out/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
